/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetreatsRouteImport } from './routes/retreats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as CampIndexRouteImport } from './routes/camp/index'
import { Route as StoriesRebeccaSpoonerRouteImport } from './routes/stories/rebecca-spooner'
import { Route as StoriesEmeliaLeeRouteImport } from './routes/stories/emelia-lee'
import { Route as StoriesAnyoneCanMakeADifferenceRouteImport } from './routes/stories/anyone-can-make-a-difference'
import { Route as CampSpecialtyRouteImport } from './routes/camp/specialty'
import { Route as CampRegisterRouteImport } from './routes/camp/register'
import { Route as CampOvernightRouteImport } from './routes/camp/overnight'
import { Route as CampGalleryRouteImport } from './routes/camp/gallery'
import { Route as CampFirstTimeRouteImport } from './routes/camp/first-time'
import { Route as CampFamilyRouteImport } from './routes/camp/family'
import { Route as CampDiscoveryRouteImport } from './routes/camp/discovery'
import { Route as CampDayRouteImport } from './routes/camp/day'
import { Route as CampDatesRouteImport } from './routes/camp/dates'

const RetreatsRoute = RetreatsRouteImport.update({
  id: '/retreats',
  path: '/retreats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampIndexRoute = CampIndexRouteImport.update({
  id: '/camp/',
  path: '/camp/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRebeccaSpoonerRoute = StoriesRebeccaSpoonerRouteImport.update({
  id: '/stories/rebecca-spooner',
  path: '/stories/rebecca-spooner',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesEmeliaLeeRoute = StoriesEmeliaLeeRouteImport.update({
  id: '/stories/emelia-lee',
  path: '/stories/emelia-lee',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesAnyoneCanMakeADifferenceRoute =
  StoriesAnyoneCanMakeADifferenceRouteImport.update({
    id: '/stories/anyone-can-make-a-difference',
    path: '/stories/anyone-can-make-a-difference',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampSpecialtyRoute = CampSpecialtyRouteImport.update({
  id: '/camp/specialty',
  path: '/camp/specialty',
  getParentRoute: () => rootRouteImport,
} as any)
const CampRegisterRoute = CampRegisterRouteImport.update({
  id: '/camp/register',
  path: '/camp/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CampOvernightRoute = CampOvernightRouteImport.update({
  id: '/camp/overnight',
  path: '/camp/overnight',
  getParentRoute: () => rootRouteImport,
} as any)
const CampGalleryRoute = CampGalleryRouteImport.update({
  id: '/camp/gallery',
  path: '/camp/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CampFirstTimeRoute = CampFirstTimeRouteImport.update({
  id: '/camp/first-time',
  path: '/camp/first-time',
  getParentRoute: () => rootRouteImport,
} as any)
const CampFamilyRoute = CampFamilyRouteImport.update({
  id: '/camp/family',
  path: '/camp/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CampDiscoveryRoute = CampDiscoveryRouteImport.update({
  id: '/camp/discovery',
  path: '/camp/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CampDayRoute = CampDayRouteImport.update({
  id: '/camp/day',
  path: '/camp/day',
  getParentRoute: () => rootRouteImport,
} as any)
const CampDatesRoute = CampDatesRouteImport.update({
  id: '/camp/dates',
  path: '/camp/dates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/retreats': typeof RetreatsRoute
  '/camp/dates': typeof CampDatesRoute
  '/camp/day': typeof CampDayRoute
  '/camp/discovery': typeof CampDiscoveryRoute
  '/camp/family': typeof CampFamilyRoute
  '/camp/first-time': typeof CampFirstTimeRoute
  '/camp/gallery': typeof CampGalleryRoute
  '/camp/overnight': typeof CampOvernightRoute
  '/camp/register': typeof CampRegisterRoute
  '/camp/specialty': typeof CampSpecialtyRoute
  '/stories/anyone-can-make-a-difference': typeof StoriesAnyoneCanMakeADifferenceRoute
  '/stories/emelia-lee': typeof StoriesEmeliaLeeRoute
  '/stories/rebecca-spooner': typeof StoriesRebeccaSpoonerRoute
  '/camp/': typeof CampIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/retreats': typeof RetreatsRoute
  '/camp/dates': typeof CampDatesRoute
  '/camp/day': typeof CampDayRoute
  '/camp/discovery': typeof CampDiscoveryRoute
  '/camp/family': typeof CampFamilyRoute
  '/camp/first-time': typeof CampFirstTimeRoute
  '/camp/gallery': typeof CampGalleryRoute
  '/camp/overnight': typeof CampOvernightRoute
  '/camp/register': typeof CampRegisterRoute
  '/camp/specialty': typeof CampSpecialtyRoute
  '/stories/anyone-can-make-a-difference': typeof StoriesAnyoneCanMakeADifferenceRoute
  '/stories/emelia-lee': typeof StoriesEmeliaLeeRoute
  '/stories/rebecca-spooner': typeof StoriesRebeccaSpoonerRoute
  '/camp': typeof CampIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/retreats': typeof RetreatsRoute
  '/camp/dates': typeof CampDatesRoute
  '/camp/day': typeof CampDayRoute
  '/camp/discovery': typeof CampDiscoveryRoute
  '/camp/family': typeof CampFamilyRoute
  '/camp/first-time': typeof CampFirstTimeRoute
  '/camp/gallery': typeof CampGalleryRoute
  '/camp/overnight': typeof CampOvernightRoute
  '/camp/register': typeof CampRegisterRoute
  '/camp/specialty': typeof CampSpecialtyRoute
  '/stories/anyone-can-make-a-difference': typeof StoriesAnyoneCanMakeADifferenceRoute
  '/stories/emelia-lee': typeof StoriesEmeliaLeeRoute
  '/stories/rebecca-spooner': typeof StoriesRebeccaSpoonerRoute
  '/camp/': typeof CampIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/retreats'
    | '/camp/dates'
    | '/camp/day'
    | '/camp/discovery'
    | '/camp/family'
    | '/camp/first-time'
    | '/camp/gallery'
    | '/camp/overnight'
    | '/camp/register'
    | '/camp/specialty'
    | '/stories/anyone-can-make-a-difference'
    | '/stories/emelia-lee'
    | '/stories/rebecca-spooner'
    | '/camp/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/retreats'
    | '/camp/dates'
    | '/camp/day'
    | '/camp/discovery'
    | '/camp/family'
    | '/camp/first-time'
    | '/camp/gallery'
    | '/camp/overnight'
    | '/camp/register'
    | '/camp/specialty'
    | '/stories/anyone-can-make-a-difference'
    | '/stories/emelia-lee'
    | '/stories/rebecca-spooner'
    | '/camp'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/retreats'
    | '/camp/dates'
    | '/camp/day'
    | '/camp/discovery'
    | '/camp/family'
    | '/camp/first-time'
    | '/camp/gallery'
    | '/camp/overnight'
    | '/camp/register'
    | '/camp/specialty'
    | '/stories/anyone-can-make-a-difference'
    | '/stories/emelia-lee'
    | '/stories/rebecca-spooner'
    | '/camp/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RetreatsRoute: typeof RetreatsRoute
  CampDatesRoute: typeof CampDatesRoute
  CampDayRoute: typeof CampDayRoute
  CampDiscoveryRoute: typeof CampDiscoveryRoute
  CampFamilyRoute: typeof CampFamilyRoute
  CampFirstTimeRoute: typeof CampFirstTimeRoute
  CampGalleryRoute: typeof CampGalleryRoute
  CampOvernightRoute: typeof CampOvernightRoute
  CampRegisterRoute: typeof CampRegisterRoute
  CampSpecialtyRoute: typeof CampSpecialtyRoute
  StoriesAnyoneCanMakeADifferenceRoute: typeof StoriesAnyoneCanMakeADifferenceRoute
  StoriesEmeliaLeeRoute: typeof StoriesEmeliaLeeRoute
  StoriesRebeccaSpoonerRoute: typeof StoriesRebeccaSpoonerRoute
  CampIndexRoute: typeof CampIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retreats': {
      id: '/retreats'
      path: '/retreats'
      fullPath: '/retreats'
      preLoaderRoute: typeof RetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/': {
      id: '/camp/'
      path: '/camp'
      fullPath: '/camp/'
      preLoaderRoute: typeof CampIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/rebecca-spooner': {
      id: '/stories/rebecca-spooner'
      path: '/stories/rebecca-spooner'
      fullPath: '/stories/rebecca-spooner'
      preLoaderRoute: typeof StoriesRebeccaSpoonerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/emelia-lee': {
      id: '/stories/emelia-lee'
      path: '/stories/emelia-lee'
      fullPath: '/stories/emelia-lee'
      preLoaderRoute: typeof StoriesEmeliaLeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/anyone-can-make-a-difference': {
      id: '/stories/anyone-can-make-a-difference'
      path: '/stories/anyone-can-make-a-difference'
      fullPath: '/stories/anyone-can-make-a-difference'
      preLoaderRoute: typeof StoriesAnyoneCanMakeADifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/specialty': {
      id: '/camp/specialty'
      path: '/camp/specialty'
      fullPath: '/camp/specialty'
      preLoaderRoute: typeof CampSpecialtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/register': {
      id: '/camp/register'
      path: '/camp/register'
      fullPath: '/camp/register'
      preLoaderRoute: typeof CampRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/overnight': {
      id: '/camp/overnight'
      path: '/camp/overnight'
      fullPath: '/camp/overnight'
      preLoaderRoute: typeof CampOvernightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/gallery': {
      id: '/camp/gallery'
      path: '/camp/gallery'
      fullPath: '/camp/gallery'
      preLoaderRoute: typeof CampGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/first-time': {
      id: '/camp/first-time'
      path: '/camp/first-time'
      fullPath: '/camp/first-time'
      preLoaderRoute: typeof CampFirstTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/family': {
      id: '/camp/family'
      path: '/camp/family'
      fullPath: '/camp/family'
      preLoaderRoute: typeof CampFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/discovery': {
      id: '/camp/discovery'
      path: '/camp/discovery'
      fullPath: '/camp/discovery'
      preLoaderRoute: typeof CampDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/day': {
      id: '/camp/day'
      path: '/camp/day'
      fullPath: '/camp/day'
      preLoaderRoute: typeof CampDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/dates': {
      id: '/camp/dates'
      path: '/camp/dates'
      fullPath: '/camp/dates'
      preLoaderRoute: typeof CampDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RetreatsRoute: RetreatsRoute,
  CampDatesRoute: CampDatesRoute,
  CampDayRoute: CampDayRoute,
  CampDiscoveryRoute: CampDiscoveryRoute,
  CampFamilyRoute: CampFamilyRoute,
  CampFirstTimeRoute: CampFirstTimeRoute,
  CampGalleryRoute: CampGalleryRoute,
  CampOvernightRoute: CampOvernightRoute,
  CampRegisterRoute: CampRegisterRoute,
  CampSpecialtyRoute: CampSpecialtyRoute,
  StoriesAnyoneCanMakeADifferenceRoute: StoriesAnyoneCanMakeADifferenceRoute,
  StoriesEmeliaLeeRoute: StoriesEmeliaLeeRoute,
  StoriesRebeccaSpoonerRoute: StoriesRebeccaSpoonerRoute,
  CampIndexRoute: CampIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
