/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetreatsRouteImport } from './routes/retreats'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as NatureSchoolRouteImport } from './routes/nature-school'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as CampIndexRouteImport } from './routes/camp/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoriesRebeccaSpoonerRouteImport } from './routes/stories/rebecca-spooner'
import { Route as StoriesEmeliaLeeRouteImport } from './routes/stories/emelia-lee'
import { Route as StoriesAnyoneCanMakeADifferenceRouteImport } from './routes/stories/anyone-can-make-a-difference'
import { Route as CampSpecialtyRouteImport } from './routes/camp/specialty'
import { Route as CampRegisterRouteImport } from './routes/camp/register'
import { Route as CampOvernightRouteImport } from './routes/camp/overnight'
import { Route as CampGalleryRouteImport } from './routes/camp/gallery'
import { Route as CampFirstTimeRouteImport } from './routes/camp/first-time'
import { Route as CampFamilyRouteImport } from './routes/camp/family'
import { Route as CampDiscoveryRouteImport } from './routes/camp/discovery'
import { Route as CampDayRouteImport } from './routes/camp/day'
import { Route as CampDatesRouteImport } from './routes/camp/dates'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminRoadmapRouteImport } from './routes/admin/roadmap'
import { Route as AdminRetreatsRouteImport } from './routes/admin/retreats'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminNatureRouteImport } from './routes/admin/nature'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminGivingRouteImport } from './routes/admin/giving'
import { Route as AdminCampRouteImport } from './routes/admin/camp'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'

const RetreatsRoute = RetreatsRouteImport.update({
  id: '/retreats',
  path: '/retreats',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const NatureSchoolRoute = NatureSchoolRouteImport.update({
  id: '/nature-school',
  path: '/nature-school',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampIndexRoute = CampIndexRouteImport.update({
  id: '/camp/',
  path: '/camp/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRebeccaSpoonerRoute = StoriesRebeccaSpoonerRouteImport.update({
  id: '/stories/rebecca-spooner',
  path: '/stories/rebecca-spooner',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesEmeliaLeeRoute = StoriesEmeliaLeeRouteImport.update({
  id: '/stories/emelia-lee',
  path: '/stories/emelia-lee',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesAnyoneCanMakeADifferenceRoute =
  StoriesAnyoneCanMakeADifferenceRouteImport.update({
    id: '/stories/anyone-can-make-a-difference',
    path: '/stories/anyone-can-make-a-difference',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampSpecialtyRoute = CampSpecialtyRouteImport.update({
  id: '/camp/specialty',
  path: '/camp/specialty',
  getParentRoute: () => rootRouteImport,
} as any)
const CampRegisterRoute = CampRegisterRouteImport.update({
  id: '/camp/register',
  path: '/camp/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CampOvernightRoute = CampOvernightRouteImport.update({
  id: '/camp/overnight',
  path: '/camp/overnight',
  getParentRoute: () => rootRouteImport,
} as any)
const CampGalleryRoute = CampGalleryRouteImport.update({
  id: '/camp/gallery',
  path: '/camp/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CampFirstTimeRoute = CampFirstTimeRouteImport.update({
  id: '/camp/first-time',
  path: '/camp/first-time',
  getParentRoute: () => rootRouteImport,
} as any)
const CampFamilyRoute = CampFamilyRouteImport.update({
  id: '/camp/family',
  path: '/camp/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CampDiscoveryRoute = CampDiscoveryRouteImport.update({
  id: '/camp/discovery',
  path: '/camp/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CampDayRoute = CampDayRouteImport.update({
  id: '/camp/day',
  path: '/camp/day',
  getParentRoute: () => rootRouteImport,
} as any)
const CampDatesRoute = CampDatesRouteImport.update({
  id: '/camp/dates',
  path: '/camp/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/admin/roadmap',
  path: '/admin/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetreatsRoute = AdminRetreatsRouteImport.update({
  id: '/admin/retreats',
  path: '/admin/retreats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNatureRoute = AdminNatureRouteImport.update({
  id: '/admin/nature',
  path: '/admin/nature',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGivingRoute = AdminGivingRouteImport.update({
  id: '/admin/giving',
  path: '/admin/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampRoute = AdminCampRouteImport.update({
  id: '/admin/camp',
  path: '/admin/camp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/giving': typeof GivingRoute
  '/nature-school': typeof NatureSchoolRoute
  '/outreach': typeof OutreachRoute
  '/retreats': typeof RetreatsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/camp': typeof AdminCampRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nature': typeof AdminNatureRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/retreats': typeof AdminRetreatsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/camp/dates': typeof CampDatesRoute
  '/camp/day': typeof CampDayRoute
  '/camp/discovery': typeof CampDiscoveryRoute
  '/camp/family': typeof CampFamilyRoute
  '/camp/first-time': typeof CampFirstTimeRoute
  '/camp/gallery': typeof CampGalleryRoute
  '/camp/overnight': typeof CampOvernightRoute
  '/camp/register': typeof CampRegisterRoute
  '/camp/specialty': typeof CampSpecialtyRoute
  '/stories/anyone-can-make-a-difference': typeof StoriesAnyoneCanMakeADifferenceRoute
  '/stories/emelia-lee': typeof StoriesEmeliaLeeRoute
  '/stories/rebecca-spooner': typeof StoriesRebeccaSpoonerRoute
  '/admin/': typeof AdminIndexRoute
  '/camp/': typeof CampIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/giving': typeof GivingRoute
  '/nature-school': typeof NatureSchoolRoute
  '/outreach': typeof OutreachRoute
  '/retreats': typeof RetreatsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/camp': typeof AdminCampRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nature': typeof AdminNatureRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/retreats': typeof AdminRetreatsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/camp/dates': typeof CampDatesRoute
  '/camp/day': typeof CampDayRoute
  '/camp/discovery': typeof CampDiscoveryRoute
  '/camp/family': typeof CampFamilyRoute
  '/camp/first-time': typeof CampFirstTimeRoute
  '/camp/gallery': typeof CampGalleryRoute
  '/camp/overnight': typeof CampOvernightRoute
  '/camp/register': typeof CampRegisterRoute
  '/camp/specialty': typeof CampSpecialtyRoute
  '/stories/anyone-can-make-a-difference': typeof StoriesAnyoneCanMakeADifferenceRoute
  '/stories/emelia-lee': typeof StoriesEmeliaLeeRoute
  '/stories/rebecca-spooner': typeof StoriesRebeccaSpoonerRoute
  '/admin': typeof AdminIndexRoute
  '/camp': typeof CampIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/giving': typeof GivingRoute
  '/nature-school': typeof NatureSchoolRoute
  '/outreach': typeof OutreachRoute
  '/retreats': typeof RetreatsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/camp': typeof AdminCampRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nature': typeof AdminNatureRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/retreats': typeof AdminRetreatsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/camp/dates': typeof CampDatesRoute
  '/camp/day': typeof CampDayRoute
  '/camp/discovery': typeof CampDiscoveryRoute
  '/camp/family': typeof CampFamilyRoute
  '/camp/first-time': typeof CampFirstTimeRoute
  '/camp/gallery': typeof CampGalleryRoute
  '/camp/overnight': typeof CampOvernightRoute
  '/camp/register': typeof CampRegisterRoute
  '/camp/specialty': typeof CampSpecialtyRoute
  '/stories/anyone-can-make-a-difference': typeof StoriesAnyoneCanMakeADifferenceRoute
  '/stories/emelia-lee': typeof StoriesEmeliaLeeRoute
  '/stories/rebecca-spooner': typeof StoriesRebeccaSpoonerRoute
  '/admin/': typeof AdminIndexRoute
  '/camp/': typeof CampIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/giving'
    | '/nature-school'
    | '/outreach'
    | '/retreats'
    | '/admin/blog'
    | '/admin/camp'
    | '/admin/giving'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nature'
    | '/admin/pages'
    | '/admin/retreats'
    | '/admin/roadmap'
    | '/admin/seo'
    | '/admin/settings'
    | '/camp/dates'
    | '/camp/day'
    | '/camp/discovery'
    | '/camp/family'
    | '/camp/first-time'
    | '/camp/gallery'
    | '/camp/overnight'
    | '/camp/register'
    | '/camp/specialty'
    | '/stories/anyone-can-make-a-difference'
    | '/stories/emelia-lee'
    | '/stories/rebecca-spooner'
    | '/admin/'
    | '/camp/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/giving'
    | '/nature-school'
    | '/outreach'
    | '/retreats'
    | '/admin/blog'
    | '/admin/camp'
    | '/admin/giving'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nature'
    | '/admin/pages'
    | '/admin/retreats'
    | '/admin/roadmap'
    | '/admin/seo'
    | '/admin/settings'
    | '/camp/dates'
    | '/camp/day'
    | '/camp/discovery'
    | '/camp/family'
    | '/camp/first-time'
    | '/camp/gallery'
    | '/camp/overnight'
    | '/camp/register'
    | '/camp/specialty'
    | '/stories/anyone-can-make-a-difference'
    | '/stories/emelia-lee'
    | '/stories/rebecca-spooner'
    | '/admin'
    | '/camp'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/giving'
    | '/nature-school'
    | '/outreach'
    | '/retreats'
    | '/admin/blog'
    | '/admin/camp'
    | '/admin/giving'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nature'
    | '/admin/pages'
    | '/admin/retreats'
    | '/admin/roadmap'
    | '/admin/seo'
    | '/admin/settings'
    | '/camp/dates'
    | '/camp/day'
    | '/camp/discovery'
    | '/camp/family'
    | '/camp/first-time'
    | '/camp/gallery'
    | '/camp/overnight'
    | '/camp/register'
    | '/camp/specialty'
    | '/stories/anyone-can-make-a-difference'
    | '/stories/emelia-lee'
    | '/stories/rebecca-spooner'
    | '/admin/'
    | '/camp/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GivingRoute: typeof GivingRoute
  NatureSchoolRoute: typeof NatureSchoolRoute
  OutreachRoute: typeof OutreachRoute
  RetreatsRoute: typeof RetreatsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCampRoute: typeof AdminCampRoute
  AdminGivingRoute: typeof AdminGivingRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNatureRoute: typeof AdminNatureRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminRetreatsRoute: typeof AdminRetreatsRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CampDatesRoute: typeof CampDatesRoute
  CampDayRoute: typeof CampDayRoute
  CampDiscoveryRoute: typeof CampDiscoveryRoute
  CampFamilyRoute: typeof CampFamilyRoute
  CampFirstTimeRoute: typeof CampFirstTimeRoute
  CampGalleryRoute: typeof CampGalleryRoute
  CampOvernightRoute: typeof CampOvernightRoute
  CampRegisterRoute: typeof CampRegisterRoute
  CampSpecialtyRoute: typeof CampSpecialtyRoute
  StoriesAnyoneCanMakeADifferenceRoute: typeof StoriesAnyoneCanMakeADifferenceRoute
  StoriesEmeliaLeeRoute: typeof StoriesEmeliaLeeRoute
  StoriesRebeccaSpoonerRoute: typeof StoriesRebeccaSpoonerRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CampIndexRoute: typeof CampIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retreats': {
      id: '/retreats'
      path: '/retreats'
      fullPath: '/retreats'
      preLoaderRoute: typeof RetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nature-school': {
      id: '/nature-school'
      path: '/nature-school'
      fullPath: '/nature-school'
      preLoaderRoute: typeof NatureSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/': {
      id: '/camp/'
      path: '/camp'
      fullPath: '/camp/'
      preLoaderRoute: typeof CampIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/rebecca-spooner': {
      id: '/stories/rebecca-spooner'
      path: '/stories/rebecca-spooner'
      fullPath: '/stories/rebecca-spooner'
      preLoaderRoute: typeof StoriesRebeccaSpoonerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/emelia-lee': {
      id: '/stories/emelia-lee'
      path: '/stories/emelia-lee'
      fullPath: '/stories/emelia-lee'
      preLoaderRoute: typeof StoriesEmeliaLeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/anyone-can-make-a-difference': {
      id: '/stories/anyone-can-make-a-difference'
      path: '/stories/anyone-can-make-a-difference'
      fullPath: '/stories/anyone-can-make-a-difference'
      preLoaderRoute: typeof StoriesAnyoneCanMakeADifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/specialty': {
      id: '/camp/specialty'
      path: '/camp/specialty'
      fullPath: '/camp/specialty'
      preLoaderRoute: typeof CampSpecialtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/register': {
      id: '/camp/register'
      path: '/camp/register'
      fullPath: '/camp/register'
      preLoaderRoute: typeof CampRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/overnight': {
      id: '/camp/overnight'
      path: '/camp/overnight'
      fullPath: '/camp/overnight'
      preLoaderRoute: typeof CampOvernightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/gallery': {
      id: '/camp/gallery'
      path: '/camp/gallery'
      fullPath: '/camp/gallery'
      preLoaderRoute: typeof CampGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/first-time': {
      id: '/camp/first-time'
      path: '/camp/first-time'
      fullPath: '/camp/first-time'
      preLoaderRoute: typeof CampFirstTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/family': {
      id: '/camp/family'
      path: '/camp/family'
      fullPath: '/camp/family'
      preLoaderRoute: typeof CampFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/discovery': {
      id: '/camp/discovery'
      path: '/camp/discovery'
      fullPath: '/camp/discovery'
      preLoaderRoute: typeof CampDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/day': {
      id: '/camp/day'
      path: '/camp/day'
      fullPath: '/camp/day'
      preLoaderRoute: typeof CampDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp/dates': {
      id: '/camp/dates'
      path: '/camp/dates'
      fullPath: '/camp/dates'
      preLoaderRoute: typeof CampDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roadmap': {
      id: '/admin/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retreats': {
      id: '/admin/retreats'
      path: '/admin/retreats'
      fullPath: '/admin/retreats'
      preLoaderRoute: typeof AdminRetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nature': {
      id: '/admin/nature'
      path: '/admin/nature'
      fullPath: '/admin/nature'
      preLoaderRoute: typeof AdminNatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/giving': {
      id: '/admin/giving'
      path: '/admin/giving'
      fullPath: '/admin/giving'
      preLoaderRoute: typeof AdminGivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/camp': {
      id: '/admin/camp'
      path: '/admin/camp'
      fullPath: '/admin/camp'
      preLoaderRoute: typeof AdminCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GivingRoute: GivingRoute,
  NatureSchoolRoute: NatureSchoolRoute,
  OutreachRoute: OutreachRoute,
  RetreatsRoute: RetreatsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCampRoute: AdminCampRoute,
  AdminGivingRoute: AdminGivingRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNatureRoute: AdminNatureRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminRetreatsRoute: AdminRetreatsRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CampDatesRoute: CampDatesRoute,
  CampDayRoute: CampDayRoute,
  CampDiscoveryRoute: CampDiscoveryRoute,
  CampFamilyRoute: CampFamilyRoute,
  CampFirstTimeRoute: CampFirstTimeRoute,
  CampGalleryRoute: CampGalleryRoute,
  CampOvernightRoute: CampOvernightRoute,
  CampRegisterRoute: CampRegisterRoute,
  CampSpecialtyRoute: CampSpecialtyRoute,
  StoriesAnyoneCanMakeADifferenceRoute: StoriesAnyoneCanMakeADifferenceRoute,
  StoriesEmeliaLeeRoute: StoriesEmeliaLeeRoute,
  StoriesRebeccaSpoonerRoute: StoriesRebeccaSpoonerRoute,
  AdminIndexRoute: AdminIndexRoute,
  CampIndexRoute: CampIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
